# Generated by Django 5.2 on 2025-04-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
    ]
