# Generated by Django 5.2 on 2025-04-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_review_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_best_seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_top_rated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
