# Generated by Django 5.2 on 2025-04-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_is_best_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_options',
        ),
    ]
