# Generated by Django 5.2 on 2025-04-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(null=True),
        ),
    ]
