# Generated by Django 5.2 on 2025-04-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(default=None),
        ),
    ]
